import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { writeFile, mkdir } from 'node:fs/promises';
const baseURL=process.env.GAME_URL||'http://127.0.0.1:5173/';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
const page=await context.newPage();
const failures=[],checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
async function check(name,fn){try{await fn();checks.push(name);console.log('PASS',name);}catch(error){failures.push({name,error:error.message});console.log('FAIL',name,error.message);}}
const game=()=>page.evaluate(()=>window.__AUIS_GAME__.state);
const pos=()=>page.evaluate(()=>window.__AUIS_GAME__.world.getPosition());
const close=()=>page.evaluate(()=>window.__AUIS_GAME__.closeModal());
const openActivity=id=>page.evaluate(id=>window.__AUIS_GAME__.openActivity(id),id);
const test=()=>page.locator('[data-action="test"]').click();
async function setRange(selector,value){await page.locator(selector).evaluate((el,value)=>{el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));},value);}
async function verifyComplete(id){await page.waitForFunction(id=>window.__AUIS_GAME__.state.completed.includes(id),id);assert.ok((await game()).completed.includes(id));await page.locator('.activity-completion').waitFor({state:'visible'});}
async function failed(){await test();await page.locator('.activity-feedback-retry').waitFor();}
async function approach(id){return page.evaluate(id=>{const w=window.__AUIS_GAME__.world;const t=w.debug.targets.find(t=>t.id===id);if(!t)throw Error('No target '+id);const nearby=[{x:t.x,z:t.z+1.1},{x:t.x+1,z:t.z},{x:t.x-1,z:t.z}];const p=nearby.find(p=>w.debug.canStand(p.x,p.z));w.testMove(p||t);return t;},id);}
await page.goto(baseURL,{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__AUIS_GAME__?.world?.debug);
await page.waitForTimeout(1200);
await mkdir('public/screenshots',{recursive:true});
await check('3D world starts without runtime errors',async()=>{assert.ok(await page.locator('#world canvas').count());assert.equal(errors.length,0);});
await page.screenshot({path:'public/screenshots/01-app-start.png'});
await page.locator('#begin').click();
await check('Walking and running respond to held keyboard input',async()=>{let a=await pos();await page.keyboard.down('w');await page.waitForTimeout(550);await page.keyboard.up('w');let b=await pos();const walk=Math.hypot(b.x-a.x,b.z-a.z);assert.ok(walk>1,'walk displacement '+walk);await page.evaluate(()=>window.__AUIS_GAME__.world.testMove({x:0,z:19}));a=await pos();await page.keyboard.down('Shift');await page.keyboard.down('w');await page.waitForTimeout(550);await page.keyboard.up('w');await page.keyboard.up('Shift');b=await pos();assert.ok(Math.hypot(b.x-a.x,b.z-a.z)>walk*1.3);});
await check('Jump lifts player and lands on solid terrain',async()=>{const y=await page.evaluate(()=>window.__AUIS_GAME__.world.player.position.y);await page.keyboard.press('Space');await page.waitForTimeout(190);const raised=await page.evaluate(()=>window.__AUIS_GAME__.world.player.position.y);assert.ok(raised>y+.35);await page.waitForTimeout(800);const landed=await page.evaluate(()=>window.__AUIS_GAME__.world.player.position.y);assert.ok(Math.abs(landed-y)<.06);});
await check('Orbit camera and zoom respond and stay above terrain',async()=>{const a=await page.evaluate(()=>window.__AUIS_GAME__.world.camera.position.toArray());await page.mouse.move(680,540);await page.mouse.down();await page.mouse.move(805,570,{steps:6});await page.mouse.up();await page.mouse.wheel(0,-200);await page.waitForTimeout(450);const b=await page.evaluate(()=>window.__AUIS_GAME__.world.camera.position.toArray());assert.ok(Math.hypot(...a.map((v,i)=>v-b[i]))>1);assert.ok(await page.evaluate(()=>{const w=window.__AUIS_GAME__.world;return w.camera.position.y>w.debug.terrainHeight(w.camera.position.x,w.camera.position.z);}));});
await check('Building and river collision prevent blocked movement',async()=>{const result=await page.evaluate(()=>{const w=window.__AUIS_GAME__.world,c=w.debug.colliders[0];return {wall:w.testMove({x:c.x,z:c.z}),river:w.testMove({x:22,z:w.debug.riverCenter(22)})};});assert.equal(result.wall,false);assert.equal(result.river,false);});
await check('Sera conversation opens with real proximity and E interaction',async()=>{await approach('sera');await page.waitForTimeout(100);await page.keyboard.press('e');await page.getByRole('dialog').waitFor();assert.ok((await page.locator('.modal-header').innerText()).includes('Sera'));await page.locator('#ask-hint').click();assert.ok(await page.locator('.hint-box').count());await page.locator('#ask-field').click();assert.ok((await page.locator('.fact-box').innerText()).includes('Preparatory'));await page.locator('#ask-task').click();});
await check('Beginner investigation fails, hints, retries, then awards journal',async()=>{await failed();await page.locator('[data-action="hint"]').click();await page.locator('.activity-feedback-hint').waitFor();await page.locator('[data-index="0"][data-direction="1"]').click();await page.locator('[data-index="1"][data-direction="1"]').click();await test();await verifyComplete('intro');});
await close();
await check('Verified Professor Switzner guide opens with E',async()=>{await approach('engineer-switzner');await page.waitForTimeout(100);await page.keyboard.press('e');assert.ok((await page.locator('.modal-header').innerText()).includes('Nathaniel Switzner'));await page.locator('#ask-field').click();assert.ok((await page.locator('.fact-box').innerText()).includes('manufacturing'));await page.locator('#ask-task').click();});
await check('Bridge model requires deck, material, and supports then repairs world',async()=>{await failed();for(let i=0;i<3;i++)await page.locator(`[data-segment="${i}"]`).click();await page.locator('[data-supports]').selectOption('2');await failed();await page.locator('[name="beam-material"][value="steel"]').check();await test();await verifyComplete('bridge');assert.equal(await page.evaluate(()=>{const w=window.__AUIS_GAME__.world;return w.debug.canStand(22,w.debug.riverCenter(22));}),true);});
await close();await page.evaluate(()=>window.__AUIS_GAME__.world.teleport('engineering'));await page.waitForTimeout(600);
await page.screenshot({path:'public/screenshots/02-engineering.png'});
await check('Professor Al-Waeli solar guide and feedback',async()=>{await approach('engineer-energy');await page.waitForTimeout(100);await page.keyboard.press('e');assert.ok((await page.locator('.modal-header').innerText()).includes('Al-Waeli'));await page.locator('#ask-field').click();assert.ok((await page.locator('.fact-box').innerText()).includes('solar'));await page.locator('#ask-task').click();});
await check('Solar angle and complete circuit power engineering workshop and first lantern',async()=>{await failed();for(let i=0;i<3;i++)await page.locator(`[data-node="${i}"]`).check();await failed();await setRange('[data-angle-control]',35);await test();await verifyComplete('energy');assert.equal(await page.locator('#lantern-count').innerText(),'1 / 9 lanterns');});
await page.screenshot({path:'public/screenshots/03-energy-discovery.png'});await close();
console.log('FIRST RELEASE CHECKPOINT: APP + Engineering tested');
await check('Computing algorithm executes, fails on obstacle, then debugs',async()=>{await openActivity('commands');await failed();await page.locator('[data-index="2"][data-shift="1"]').click();await test();await verifyComplete('commands');});await close();
await check('Business budget observes demand and solves allocation',async()=>{await openActivity('market');await failed();await setRange('[data-budget="inventory"]',30);await setRange('[data-budget="team"]',20);await setRange('[data-budget="sign"]',10);await test();await verifyComplete('market');});await close();
await check('English compares records and rejects unsupported reports',async()=>{await openActivity('story');await failed();await page.locator('[data-evidence][value="repair"]').check();await page.locator('[data-evidence][value="log"]').check();await page.locator('[data-conclusion]').selectOption('storm');await test();await verifyComplete('story');});await close();
await check('Laboratory requires comparable recorded simulated observations',async()=>{await openActivity('samples');await failed();await setRange('[data-focus]',3);for(const id of ['A','B','C']){await page.locator(`[data-sample="${id}"]`).click();await page.locator('[data-record]').click();}await page.locator('[data-answer]').selectOption('B');await test();await verifyComplete('samples');});await close();
await check('Council negotiation shows social constraints and shared agreement',async()=>{await openActivity('council');await failed();await setRange('[data-share]',50);await page.locator('[data-plan]').selectOption('joint');await test();await verifyComplete('council');});await close();
await check('Mathematics reflection model observes rays and receives aligned light',async()=>{await openActivity('light');await failed();await setRange('[data-mirror="0"]',-21);await setRange('[data-mirror="1"]',-6);await test();await verifyComplete('light');});await page.screenshot({path:'public/screenshots/04-reflection-puzzle.png'});await close();
await check('Dentistry model assembles four structures',async()=>{await openActivity('tooth');await failed();for(const id of ['enamel','dentin','pulp','root']){await page.locator(`[data-part="${id}"]`).click();await page.locator(`[data-slot="${id}"]`).click();}await test();await verifyComplete('tooth');});await close();
await check('Pharmacy sorts imaginary ingredients and tests fictional formulation',async()=>{await openActivity('ingredients');await failed();for(const[id,value]of [['dew','carrier'],['petal','colorant'],['silk','binder']])await page.locator(`[data-ingredient="${id}"]`).selectOption(value);for(const[id,change]of [['carrier','1'],['colorant','-1'],['binder','1']])await page.locator(`[data-portion="${id}"][data-change="${change}"]`).click();await test();await verifyComplete('ingredients');});await close();
await check('All nine regions have guide, companion, and reachable playable activity',async()=>{const result=await page.evaluate(()=>{const w=window.__AUIS_GAME__.world;return w.regions.map(r=>({id:r.id,faculty:w.debug.targets.some(t=>t.regionId===r.id&&(t.type==='faculty'||r.id==='village'&&t.id==='sera')),support:w.debug.targets.some(t=>t.regionId===r.id&&t.type==='support'),activity:w.debug.targets.some(t=>t.regionId===r.id&&t.type==='activity')}));});for(const r of result){assert.ok(r.faculty,r.id+' faculty');assert.ok(r.support,r.id+' support');assert.ok(r.activity,r.id+' activity');}for(const id of ['computing','business','english','medical','social','mathematics','dentistry','pharmacy']){await page.evaluate(id=>window.__AUIS_GAME__.world.teleport(id),id);assert.ok(await page.evaluate(()=>{const w=window.__AUIS_GAME__.world,p=w.getPosition();return w.debug.canStand(p.x,p.z);}));}});
await check('Final beacon reward reaches nine lanterns without duplicate replay rewards',async()=>{assert.equal(await page.locator('#lantern-count').innerText(),'9 / 9 lanterns');const before=(await game()).completed.length;await openActivity('energy');for(let i=0;i<3;i++)await page.locator(`[data-node="${i}"]`).check();await setRange('[data-angle-control]',35);await test();assert.equal((await game()).completed.length,before);await close();await approach('beacon');await page.keyboard.press('e');assert.ok((await page.locator('.modal-content').innerText()).includes('You brought the light home'));});await page.screenshot({path:'public/screenshots/05-beacon-restored.png'});await close();
await check('Archive classifies colleges, departments, minors, APP and source audit',async()=>{await page.evaluate(()=>window.__AUIS_GAME__.openArchive('dentistry'));assert.ok((await page.locator('#archive-entry').innerText()).toUpperCase().includes('COLLEGE'));await page.locator('[data-entry="mathematics"]').click();assert.ok((await page.locator('#archive-entry').innerText()).includes('Minors'));assert.equal(await page.locator('#archive-entry').getByText('Degree programs',{exact:true}).count(),0);await page.locator('[data-entry="audit"]').click();assert.ok((await page.locator('#archive-entry').innerText()).includes('unresolved'));assert.ok(await page.locator('#archive-entry a[href*="Academic%20Catalog"]').count());await page.locator('[data-entry="village"]').click();assert.ok((await page.locator('#archive-entry').innerText()).includes('PREPARATORY PROGRAM'));});await page.screenshot({path:'public/screenshots/06-moulakis-archive.png'});await close();
await check('Map and journal keyboard shortcuts, discovered fast travel and quest records',async()=>{await page.keyboard.press('m');await page.locator('[data-region="engineering"]').click();await page.locator('#travel').click();assert.equal((await game()).region,'engineering');await page.keyboard.press('j');assert.equal(await page.locator('.quest-row.completed').count(),11);await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);});
await check('Saved progress, position, and settings survive browser reload',async()=>{await page.locator('[data-menu="settings"]').click();await page.locator('#quality').selectOption('balanced');await page.locator('#reducedMotion').check();await page.locator('#save-now').click();const before=await game();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__AUIS_GAME__?.world);const after=await game();assert.deepEqual(after.completed,before.completed);assert.equal(after.settings.quality,'balanced');assert.equal(after.settings.reducedMotion,true);assert.ok(Math.hypot(after.position.x-before.position.x,after.position.z-before.position.z)<.1);});
await check('Reset confirms intent and restores a fresh journey',async()=>{await page.locator('[data-menu="settings"]').click();await page.locator('#new-journey').click();assert.ok((await game()).completed.length>0);await page.locator('#cancel-reset').click();assert.ok((await game()).completed.length>0);await page.locator('#new-journey').click();await page.locator('#confirm-reset').click();assert.equal((await game()).completed.length,0);assert.equal((await game()).region,'village');});
const performance=[];
for(const quality of ['high','balanced']){await page.evaluate(quality=>{window.__AUIS_GAME__.world.setSettings({quality});window.__AUIS_GAME__.world.teleport('village');},quality);await page.waitForTimeout(2500);const samples=[];for(let i=0;i<4;i++){samples.push(await page.evaluate(()=>window.__AUIS_GAME__.metrics));await page.waitForTimeout(350);}performance.push({quality,samples});}
await check('Small viewport retains usable menus, dialogs, and touch controls',async()=>{await page.setViewportSize({width:390,height:844});await page.locator('[data-menu="archive"]').click();assert.ok(await page.getByRole('dialog').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'public/screenshots/07-mobile-archive.png'});await close();});
await check('No browser runtime errors across full journey',async()=>assert.deepEqual(errors,[]));
const report={testedAt:new Date().toISOString(),browser:'Google Chrome '+browser.version(),mode:'headless, native WebGL (not forced software rendering)',os:'macOS 15.5, arm64',device:'MacBook Pro (MacBookPro18,3), Apple M1 Pro, 8-core CPU, 16 GB memory',viewport:'1440×900, device scale1; responsive390×844',url:baseURL,passed:checks,failures,errors,performance};
await writeFile('docs/browser-results.json',JSON.stringify(report,null,2)+'\n');
await browser.close();console.log(JSON.stringify({passed:checks.length,failures,performance},null,2));if(failures.length)process.exitCode=1;
